"seed" :
"rate" : 100
"render" : True
"n_substeps" : 2
"state_dim" : 5
"n_traj_pts" : 15
"randomize_env" : False
"allow_latent_input" : False
"latent_dim" : 4
"allow_lte" : False
"lte_prob" : 0.3
"wp_sample_dist" : 0.17
"wp_reach_dist" : 0.3
"max_steps" : 300
"traj_smoothness" : 500
"traj_smoothness_variance" : 200
"act_pen" : 0.013
"enforce_bilateral_symmetry" : False
"use_engine_2" : False