"seed" :
"rate" : 100
"render" : True
"n_substeps" : 2
"randomize_env" : False
"state_dim" : 3
"latent_dim" : 4
"car_xml" : "one_car_maize"
"rew_type" : "traj" # traj/free
"deadzone" : 0.25 # traj/free
"n_blocks" : 8

# LTE
"allow_lte" : False
"use_hybrid_engine" : False
"lte_prob" : 1.0
"discriminator_thresh" : 0.5

# Params
"allow_latent_input" : False
"use_latent_input_estimator" : False
"train_latent_input_estimator" : False
"param_batchsize" : 64
"param_estimator_lr" : 0.001

"n_traj_pts" : 15
"wp_sample_dist" : 0.17
"wp_reach_dist" : 0.5
"max_steps" : 300
"traj_smoothness" : 500
"traj_smoothness_variance" : 200
"act_pen" : 0.013
"enforce_bilateral_symmetry" : False
