"seed" :
"rate" : 100
"render" : True
"n_substeps" : 10
"state_dim" : 5
"n_traj_pts" : 15
"randomize_env" : False
"allow_latent_input" : False
"latent_dim" : 5
"allow_lte" : False
"lte_prob" : 0.3
"wp_sample_dist" : 0.17
"wp_reach_dist" : 0.3
"max_steps" : 400
"traj_smoothness" : 400
#"traj_smoothness_variance" : 200