# Train config
"train" : True
"render" : False
"default_session_ID" : "TRN"
"cma_std" : 0.3
"iters" : 400000
"n_trials" : 2000

"algo_name" : "TD3"
"policy_name" : "MlpPolicy" # "MlpLstmPolicy", "MlpPolicy"
"n_envs" : 1
"gamma" : 0.99
"learning_rate" : 0.001
"buffer_size" : 100000
"learning_starts" : 30000
"batch_size" : 140
"tau" : 0.005
"policy_delay" : 2
"target_policy_noise" : 0.1
"target_noise_clip" : 0.1
"policy_hid_dim" : 128
"verbose" : 1
"tensorboard_log" : True
"ou_sigma" : 0.7
"ou_theta" : 0.01
"ou_dt" : 2.0

