# Train config
"train" : False
"render" : True
"default_session_ID" : "TRN"
"iters" : 8000000
"env" : "default" # default/maize

# RL algo
"algo_name" : "A2C"
"policy_name" : "MlpPolicy" # "MlpLstmPolicy", "MlpPolicy"
"n_envs" : 4
"gamma" : 0.99
"n_steps" : 30
"vf_coef" : 0.6
"ent_coef" : 0.000000
"max_grad_norm" : 0.75
"learning_rate" : 0.0002 # 0.0002
"verbose" : 1
"full_tensorboard_log" : False
"policy_hid_dim" : 256
"log_prefix" : "be1"
"rew_thresh" : 44
"deterministic_eval" : False


