# Train config
"train" : True
"render" : True
"default_session_ID" : "TRN"
"cma_std" : 0.3
"iters" : 100000
"n_trials" : 2000

"algo_name" : "SAC"
"policy_name" : "MlpPolicy" # "MlpLstmPolicy", "MlpPolicy"
"n_envs" : 1
"gamma" : 0.99
"learning_rate" : 0.001
"buffer_size" : 100000
"learning_starts" : 20000
"batch_size" : 256
"tau" : 0.005
"policy_delay" : 2
"target_policy_noise" : 0.1
"target_noise_clip" : 0.1
"policy_hid_dim" : 196
"verbose" : 1
"tensorboard_log" : True
"ou_sigma" : 0.1
"ou_theta" : 0.001
"ou_dt" : 0.4
"ent_coef" : 0.00001
