"n_traj" : 10
"traj_len" : 600
"traj_sampling_dist" : 0.17
"traj_jump_iters" : 100
"contiguous_traj_len" : 300
"n_waypoints" : 15
"add_action_to_traj" : False
"policy_lr" : 0.001
"param_estimator_lr" : 0.003
"w_decay" : 0.001
"trn_iters" : 5000
"batchsize" : 128
"recurrent_batchsize" : 10
"n_latent_params" : 5
"mlp_hid_dim" : 256
