"n_dataset_pts" : 4000
"max_num_wp" : 50
"max_steps" : 500
"policy_lr" : 0.004
"w_decay" : 0.0005
"batchsize" : 256
"tep_iters" : 8000
"n_epochs" : 32
"n_traj_update" : 196
"n_eval" : 100
"deterministic_eval" : False
"plot_trajs" : False
"render" : False
"n_step_opt" : 10
"traj_opt_rate" : 0.015
"traj_barrier_coeff" : 0.3
"traj_last_pt_coeff" : 10

