"n_dataset_pts" : 2000
"max_num_wp" : 50
"max_steps" : 500
"policy_lr" : 0.005
"w_decay" : 0.0007
"batchsize" : 256
"tep_iters" : 7000 # 7000
"n_epochs" : 32
"n_traj_update" : 64 # 128
"n_eval" : 30
"deterministic_eval" : False
"plot_trajs" : False
"render" : False
"n_step_opt" : 10 # 15
"traj_opt_rate" : 0.015 # 0.015
"traj_barrier_coeff" : 0.3
"traj_last_pt_coeff" : 10
"barrier_pt_thresh_dist" : 0.15
"tep_class" : "MLP" # MLP, MLPDEEP, RNN, RNN2, TX
"env" : "MAIZE" # DEF, MAIZE
"optimizer" : "ADAM" # SGD, ADAM, LBFGS


